name: build-and-publish-lxc
run-name: Build
on: [push]
jobs:
  build-lxc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Setup distrobuilder"
        run: sudo snap install distrobuilder --classic
        shell: "bash"
      - name: "Setup debootstrap"
        run: sudo apt install debootstrap
        shell: "bash"
      - run: sudo distrobuilder build-lxc debian.yaml -o image.architecture=amd64 --compression gzip
        shell: "bash"
      - run: "mv rootfs.tar.gz debian-traefik_2.10.5_amd64.tar.gz"
      - name: Create new release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          gh release create ${{github.ref_name}} \
          --title "${{github.ref_name}}" \
          --generate-notes \
          --target "${{github.sha}}" \
          debian-traefik_2.10.5_amd64.tar.gz
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    permissions:
      contents: write          